#!/usr/bin/bash

function update_time {
  curr_date=$(date +"%a %b %d %Y")
  curr_time=$(date +"%H:%M:%S")
  curr_secs=$(date +"%s")
}

function start_entry {
  update_time
  last_date=$curr_date
  last_time=$curr_time
  last_secs=$curr_secs
  update_entry
}

function update_entry {
  update_time
  duration=$(date -u -d @"$((curr_secs-last_secs))" +"%H:%M:%S")
  curr_entry="  ${duration} | ${last_date} | ${last_time} - ${curr_time}"
}

function show_entry {
  echo "$curr_entry"
}

function do_over {
  echo -ne "\033[1A"
}

start_entry
show_entry

while true; do
  update_entry
  do_over
  show_entry
  sleep 0.5
done
