#!/usr/bin/bash

function update_time {
  curr_date=$(date +"%a %b %d %Y")
  curr_time=$(date +"%H:%M:%S")
}

function update_line {
  update_time
  curr_line="??:?? | ${curr_date} | ${curr_time} - ${curr_time}"
}

do_over="echo -ne \033[1A"

update_line
echo "$curr_line"
sleep 1

update_line
$do_over
echo "$curr_line"
